# Site settings
title: hoyouly
subtitle: 积跬步，至千里。
keywords: hoyouly
description: 我要用自己的双手，敲出一个美好未来
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hoyouly.fun" # 你的域名
page_no_title: "hoyouly's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: hoyouly
email: hoyouly@163.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Pageinate settings
paginate: 6 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Google Analytics
google_analytics_id: 'UA-115937602-1'            # Format: UA-xxxxxx-xx
ga_domain: www.hoyouly.fun              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# 百度统计
baidu_tongji_id: 3dc2b6bcb95de72ae7a543091ad0539e

# Code hub settings
# codehub: # 代码仓库
#   - title: Github
#     url: https://github.com/hoyouly


valine:
  enable: true
  app_id:  JTO4YojfpM7Ex3zEsxQPmnhN-gzGzoHsz
  app_key: FpB8suHIAtQkv9jikktpNSmV
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
  guest_info: nick,mail,link
  pageSize: 10
